Change shells to the correct zsh. Dont clobber the .zshrc

diff --git a/src/applications/zsh-installed b/src/applications/zsh-installed
--- a/src/applications/zsh-installed
+++ b/src/applications/zsh-installed
@@ -5,19 +5,39 @@
 requires log-writer
 requires package-manager
 
-
 if [[ "$SHELL" =~ 'zsh' ]]; then
     log_trace 'Already have zsh'
-    return 0
-fi
 
-if ! try_install 'zsh'; then
+elif ! try_install 'zsh'; then
     log_error $'Couldn\'t install zsh and I don\'t know how to manually do it'
     exit 1
+
 fi
 
-echo '' > "$HOME/.zshrc"
-sudo chsh -s $(which zsh)
+if [ ! -e "$HOME/.zshrc" ]; then
+  echo '' > "$HOME/.zshrc"
+fi
 
+if [[ ! "$SHELL" =~ 'zsh' ]]; then
+  case "$PACKAGE_MANAGER" in
+    'pacman')
+      zsh_loc=$(which zsh)
+    ;;
+    'homebrew')
+      zsh_loc=$(find /usr/local/Cellar/zsh/ -type f -name zsh)
+    ;;
+  esac
+
+  if [ ! "$zsh_loc" ]; then
+    log_error $'Couldn\t find zsh'
+    exit 1
+  fi
+
+  if ! grep "$zsh_loc" /etc/shells; then
+    sudo sh -c "echo '$zsh_loc' >> /etc/shells"
+  fi
+
+  chsh -s "$zsh_loc"
+fi
 
 log_message 'You have zsh'
