Make the script less noisy by shoving all stdout into a trace file

diff --git a/src/logwriter b/src/logwriter
--- a/src/logwriter
+++ b/src/logwriter
@@ -1,53 +1,52 @@
 # Exports
-#	log_error
-# log_warning
-#	log_trace
-#	log_message
+#	  log_error
+#   log_warning
+#   log_trace
+#   log_message
 #
-# Dependencies
 
-if type log_error; then
+if type log_error &> /dev/null; then
   log_trace 'Already setup log streams'
   return 0
 fi
 
+exec 3>&1
+trap 'exec 1>&3 3>&-' exit
+exec 1> ${TRACE_OUTPUT:-/dev/null}
+
 # Log the message to stderr after marking it as error
-# Tees to TRACE_OUTPUT if available
 log_error () {
-  echo "error: $1 :(" | tee ${TRACE_OUTPUT:-/dev/null} 1>&2
-  echo "fatal: $1" >>  ${INSTALL_LOG_OUT:-/dev/null}
+  echo "error: $1 :(" | tee -a ${TRACE_OUTPUT:-/dev/null} ${INSTALL_LOG_OUT:-/dev/null} > /dev/stderr
 }
 export -f log_error
 
+# Log the message to stderr after marking it as message
+log_message () {
+	echo "message: $1"'!' | tee -a ${TRACE_OUTPUT:-/dev/null} ${INSTALL_LOG_OUT:-/dev/null} > /dev/stderr
+}
+export -f log_message
+
 # Log the message to TRACE_OUTPUT, or stderr if TRACE_OUTPUT is null
 log_trace () {
-	echo "trace: $1" >> ${TRACE_OUTPUT:-/dev/stderr}
+  echo "trace: $1" | tee -a ${TRACE_OUTPUT:-/dev/stderr} ${INSTALL_LOG_OUT:-/dev/null} > /dev/null
 }
 export -f log_trace
 
 # Log the message to TRACE_OUTPUT, or stderr if TRACE_OUTPUT is null
 log_warning () {
-  echo "warning: $1..." > ${TRACE_OUTPUT:-/dev/stderr}
+  echo "warning: $1..." | tee -a ${TRACE_OUTPUT:-/dev/stderr} ${INSTALL_LOG_OUT:-/dev/null} > /dev/null
 }
 export -f log_warning
-
-# Log the message to stderr after marking it as message
-# Tees to TRACE_OUTPUT if available
-log_message () {
-	echo "message: $1!" | tee ${TRACE_OUTPUT:-/dev/null} 1>&2
-  echo "$1" >>  ${INSTALL_LOG_OUT:-/dev/null}
-}
-export -f log_message
 
 
 if [ "$TRACE_OUTPUT" ]; then
   echo '' > $TRACE_OUTPUT
 else
-  log_warning $'You don\'t have a $TRACE_OUTPUT defined. We\'re going to log to stderr'
+  log_warning $'You don\'t have a $TRACE_OUTPUT defined.'
 fi
 
 if [ "$INSTALL_LOG_OUT" ]; then
   echo '' > $INSTALL_LOG_OUT
 else
-  log_warning $'You don\'t have a $INSTALL_LOG_OUT defined. We won\'t log to a file'
+  log_warning $'You don\'t have a $INSTALL_LOG_OUT defined.'
 fi
