Tidy all shell files and vim files

diff --git a/XDG_BIN_HOME/git-scam b/XDG_BIN_HOME/git-scam
--- a/XDG_BIN_HOME/git-scam
+++ b/XDG_BIN_HOME/git-scam
@@ -10,19 +10,18 @@
 # TODO: Make a version that doesn't commit everything
 
 if ! [ "$1" ]; then
-  echo 'error: You didnt specify a commit message'
-  exit 1
+	echo 'error: You didnt specify a commit message'
+	exit 1
 fi
 
-git add -A 
+git add -A
 git status
 
 read -p 'Do you still want to commit all? [Yn]' confirmed
-if [ "$confirmed" = 'Y' ]
-then
-  echo
-  git commit -m "$1"
-  echo
+if [ "$confirmed" = 'Y' ]; then
+	echo
+	git commit -m "$1"
+	echo
 else
-  git reset > /dev/null
+	git reset >/dev/null
 fi
